Feature/cc mt service authentication
bunjovis/ConnectedCircularity pull request #17
Opened 2022-10-21 18:13 UTC by MSurvonen

2022-10-23 08:06 UTC, bunjovis requested changes

2022-10-23 08:06 UTC, bunjovis commented on cc-mt-service/.env.example
> +<<<<<<< HEAD
this file has merge conflicts, it should be resolved. Only one port and remove the other merge conflict related stuff (<<<<< HEAD, =======, >>>>>>> 043e03....)

2022-10-23 08:06 UTC, bunjovis commented on cc-mt-service/src/app.ts
> +      url: 'https://test-auth.materiaalitori.fi/connect/token?grant_type=client_credentials&scope=ym-tietoalusta-api',
scope in the url should come from the variable scope.

2022-10-23 09:55 UTC, OpaJaa submitted a review, later dismissed
For me these look good.

2022-10-24 12:52 UTC, rvsape commented on cc-mt-service/src/app.ts
> +    var axios = require('axios');
imports from packages should be on top of the file, plus using import syntax and const instead of var is preferred

2022-10-24 12:56 UTC, rvsape commented on cc-mt-service/src/app.ts
> +    var axios = require('axios');
npm run check gives some errors regarding this

2022-10-24 13:52 UTC, rvsape commented on cc-mt-service/src/app.ts
> +    var data = qs.stringify({
const/let instead of var

2022-10-24 14:20 UTC, rvsape requested changes
- fix **npm run check** errors
- **npm run dev** error: 'ts-node' is not recognized as an internal or external command,

2022-10-24 17:32 UTC, MSurvonen commented
@rvsape tested "npm run dev" and works for me normally. What to do because no errors to fix for me

2022-10-25 02:03 UTC, alihussain03 commented
For me it looks fine. i have tested using npm start and npm run check. npm run dev is giving error which needs to be fix 
![image](https://user-images.githubusercontent.com/70361355/197664776-76e8aa59-edcd-4d6f-b654-8e7e44e51f98.png)

2022-10-25 05:01 UTC, rvsape commented
> 

missing dependency? npm i ts-node

2022-10-25 11:18 UTC, rvsape approved these changes

2022-10-26 13:44 UTC, bunjovis approved these changes

2022-10-27 05:01 UTC, merged