Feature/cc mt service post data route
bunjovis/ConnectedCircularity pull request #23
Opened 2022-10-31 07:33 UTC by MSurvonen

2022-11-01 15:57 UTC, bunjovis requested changes

2022-11-01 15:57 UTC, bunjovis commented on cc-mt-service/src/routes/mtServiceRoutes.ts
> +    res.send(response);
This needs some error handling around, take a look at cc-pk-service/src/routes/pkServiceRoutes.ts for example

2022-11-01 15:57 UTC, bunjovis commented on cc-mt-service/src/handleData.ts
> +        const dataObject:AdvertData = {
Add the dataObject as a parameter to this postAdvert() function so this can be used to post anything

2022-11-01 15:57 UTC, bunjovis commented on cc-mt-service/src/routes/mtServiceRoutes.ts
> +    const response = await postAdvert();
here, give the objectData to postAdvert() function. The object data should come from request body like in the openapi.yaml. You can access the request body attributes like this: req.body.attribute, for example req.body.title.

2022-11-04 18:04 UTC, MSurvonen commented
Doesn't work. Tried to use req.body.data but it is undefined. Used same data which was earlier as a dataObject in postAdvert function. Req.body shows different for some reason

2022-11-07 18:12 UTC, hannakortetjarvi commented on cc-mt-service/src/app.ts
I wasn't able to comment on the lines directly, but in this file (app.ts) the variables cId, cSecret and scope are now unused and can be removed.

2022-11-08 07:02 UTC, OpaJaa commented on cc-mt-service/src/types.ts
> +        regions: [
I think I'm missing this in the backend so will update there when this is merged. Good job!

2022-11-08 07:09 UTC, MSurvonen commented
I don't actually know if we need regions array or if some service is using it. But it has to be when posting data to Materiaalitori, at least an empty array.

2022-11-09 15:15 UTC, bunjovis approved these changes

2022-11-09 15:31 UTC, merged