Feature/pk service request header
bunjovis/ConnectedCircularity pull request #24
Opened 2022-11-02 08:57 UTC by hannakortetjarvi

2022-11-02 15:53 UTC, bunjovis requested changes
This is not working for me. I had to add 
`import dotenv from 'dotenv';

dotenv.config();`
to cc-pk-service/app.ts and then it started working. Odd that you're not even touching that part in app.ts in this pull request, maybe dotenv worked fine because it was included in another file?

2022-11-02 19:32 UTC, hannakortetjarvi commented
Noticed eslint files have disappeared(?) so 'npm run check' isn't working atm. I'm working on that

2022-11-03 13:30 UTC, bunjovis requested changes
In your own routes, also use the standard headers for token. meaning, the correct header where the token is should be Authorization, and the value should be "Bearer <token>"

2022-11-04 10:45 UTC, OpaJaa requested changes
Sent my version of resolving tokens in teams chat to you. If suggestions, can change my implementation also. But either way me or you or both have to do changes :)

2022-11-04 10:45 UTC, OpaJaa commented on cc-pk-service/src/routes/pkServiceRoutes.ts
> +    const token:any = req.headers.token ?? '';
Maybe change to req.headers.authorization, then split the token as "Bearer" is left in it. Sent you code snippets to check.

2022-11-04 10:45 UTC, OpaJaa commented on cc-pk-service/src/handleData.ts
> -}
If doing a new getToken -function for splitting and returning, you could add it here. Code snippet also from this in teams chat

2022-11-06 12:59 UTC, bunjovis requested changes

2022-11-06 12:59 UTC, bunjovis commented on cc-pk-service/.env.example
> +<<<<<<< HEAD
Fix merge conflicts in this file

2022-11-09 09:31 UTC, MSurvonen commented
I had to write npm install cors and started to work after that

2022-11-09 15:37 UTC, bunjovis approved these changes

2022-11-10 13:13 UTC, OpaJaa approved these changes

2022-11-10 13:13 UTC, OpaJaa commented on cc-pk-service/.env.example
> +>>>>>>> main
I think this has the same conflicts remaining as was in my repo. Should remove those 👍

2022-11-10 13:21 UTC, merged