Feature/cc mt service request header
bunjovis/ConnectedCircularity pull request #29
Opened 2022-11-09 13:45 UTC by MSurvonen

2022-11-09 15:34 UTC, bunjovis requested changes

2022-11-09 15:34 UTC, bunjovis commented on cc-mt-service/src/routes/mtServiceRoutes.ts
> +mtRouter.post('/advert', async (req:Request, res:Response) => {
So, this function needs some changes. First, check that there is token. For example, add check after the line 11, if wholeToken equals empty string. If yes, error response should be sent. Error message would be something like "No token available" and error status would be 401. Then, when you get the response from postAdvert, check if response.status is 401. That means it the token is invalid and you should set your own error message  again to "Invalid token" or something like that, and error status to 401.

2022-11-10 14:11 UTC, OpaJaa requested changes

2022-11-10 14:11 UTC, OpaJaa commented on cc-mt-service/src/routes/mtServiceRoutes.ts
> +mtRouter.post('/advert', async (req:Request, res:Response) => {
Your openapi.yaml has /v1/advert and this only /advert. For similarity to other services I suggest to change this to /v1/advert

2022-11-10 14:13 UTC, OpaJaa commented
Left a comment about the path but then saw that it was correct as app.ts had the missing /v1. So removed my earlier comment.

2022-11-15 17:30 UTC, bunjovis approved these changes

2022-11-16 06:11 UTC, merged