Initial setup for Materialtori service
bunjovis/ConnectedCircularity pull request #4
Opened 2022-10-02 08:59 UTC by alihussain03

2022-10-02 11:24 UTC, rvsape commented
Please make a separate PR for docker related changes

2022-10-02 11:28 UTC, alihussain03 commented
i think docker changes in separate PR will not make sense as in main branch we don't have much things. for running  the docker files, we should have some running project.

2022-10-02 11:33 UTC, rvsape commented
maybe the the docker stuff needs to wait that we have something in main

2022-10-02 11:34 UTC, alihussain03 commented
yeah maybe that could be one option. now i can remove the docker files and wait for the PR approval.

2022-10-02 16:39 UTC, rvsape commented on cc_materiaalitori_service_setup/.env
> +PORT=8000
.env - files should be ignored, so rename to .env-example

2022-10-02 16:40 UTC, rvsape commented on cc_materiaalitori_service_setup/README.md
> +1. Move into the cc_materiaalitori_service_setup directory
No need for this line, since README is in the desired location already

2022-10-02 16:42 UTC, rvsape commented on cc_materiaalitori_service_setup/tsconfig.json
> +          "outDir": "dist"
add "strict": true for better type checking

2022-10-02 16:57 UTC, rvsape commented on cc_materiaalitori_service_setup/README.md
> +Additional script: Run ```npm run check``` to check the file for TypeScript errors/warnings with eslint
eslint script does not work

2022-10-02 16:59 UTC, rvsape commented on cc_materiaalitori_service_setup/tsconfig.json
> +{
formatting

2022-10-02 17:01 UTC, rvsape commented on cc_materiaalitori_service_setup/package.json
> +    "readline-sync": "^1.4.10"
why readline-sync?

2022-10-02 17:06 UTC, rvsape commented
rename folder: cc-materiaalitori-service

2022-10-06 12:37 UTC, OpaJaa commented
> rename folder: cc-materiaalitori-service

This is still missing.

2022-10-06 12:39 UTC, OpaJaa commented
> > rename folder: cc-materiaalitori-service
> 
> This is still missing.

And actually could the folder be named cc-mt-service like cc-pk-service is named? @rvsape

2022-10-08 04:58 UTC, bunjovis commented
@alihussain03 are you adding those changes suggested by @OpaJaa ? what about @rvsape , do you agree with changes ali has done after your review?

2022-10-08 05:58 UTC, rvsape requested changes
Folder name: change to cc-mt-service

2022-10-08 10:26 UTC, OpaJaa requested changes
Typo in the folder name cc-mt-servcie -> cc-mt-service

2022-10-08 10:32 UTC, OpaJaa submitted a review, later dismissed

2022-10-08 12:01 UTC, rvsape commented on cc-mt-service/README.md
> +1. Make sure you are in cc_materiaalitori_service_setup directory
directory name change

2022-10-08 12:02 UTC, OpaJaa approved these changes, later dismissed

2022-10-08 12:02 UTC, rvsape commented on cc-mt-service/package.json
> +  "name": "cc_materiaalitori_service_setup",
directory name change

2022-10-08 12:03 UTC, rvsape requested changes
directory name change updates to README and package.json files

2022-10-08 12:08 UTC, rvsape approved these changes

2022-10-08 12:10 UTC, OpaJaa approved these changes

2022-10-08 12:10 UTC, merged