initial set up for UI
bunjovis/ConnectedCircularity pull request #5
Opened 2022-10-05 16:48 UTC by olivena

2022-10-05 20:26 UTC, rvsape commented
Alright. But you can push into git without making a PR too :)

2022-10-06 12:34 UTC, OpaJaa commented
You could pull main branch to this and add a readme to /cc-ui/ with usage directions.

2022-10-06 15:07 UTC, bunjovis commented
@olivena are you still going to add code to this pull request before we should approve (based on your comment)? let us know when its ready

2022-10-07 09:49 UTC, olivena commented
I cleaned the code a bit, if its okay that i add the readme after merging, it is okay to merge

2022-10-08 05:01 UTC, bunjovis commented
No, add the readme before.

2022-10-08 10:38 UTC, OpaJaa commented
> I cleaned the code a bit, if its okay that i add the readme after merging, it is okay to merge

You would need to do a new pull request for the readme or add it in a later one as you cannot push changes straight to main. So a readme with the info needed at this time should be added. Like how to run the service etc.

2022-10-10 06:11 UTC, hannakortetjarvi reviewed
I think you can also remove the react.svg -file, since you are using vite.svg as a favicon

2022-10-10 06:11 UTC, hannakortetjarvi commented on cc-ui/src/App.css
> +.logo {
You can make this App.css file look cleaner by removing the parts that aren't used in the program. For example, I don't think logo was mentioned in the code anywhere

2022-10-10 09:31 UTC, olivena commented
I think the initial set up for UI is finally ready, I added readme and did more cleaning up, im sorry I didn't have time last week to do these final touches.

2022-10-10 13:49 UTC, rvsape commented on cc-ui/src/main.tsx
> +  <React.StrictMode>
Should the App-component be wrapped with ChakraProvider?

2022-10-10 13:50 UTC, rvsape commented on cc-ui/src/App.tsx
> +import { ChakraProvider } from '@chakra-ui/react'
unused import

2022-10-10 13:51 UTC, rvsape commented on cc-ui/package.json
> +  "dependencies": {
chakra-ui is missing

2022-10-10 13:53 UTC, rvsape commented on cc-ui/package.json
> +  "dependencies": {
npm i @chakra-ui/react @emotion/react @emotion/styled framer-motion

2022-10-10 13:54 UTC, rvsape requested changes
Chakra-UI is missing from packages, and is not used correctly

2022-10-11 14:22 UTC, rvsape commented on cc-ui/src/App.tsx
> +    <ChakraProvider>
It is enough to use the ChakraProvider wrapper in the main.tsx, so it can be removed here

2022-10-11 14:23 UTC, rvsape requested changes
Duplicate use of ChakraProvider. It is enough to use it only in the main.tsx file

2022-10-11 18:43 UTC, rvsape approved these changes

2022-10-12 05:49 UTC, hannakortetjarvi approved these changes

2022-10-12 14:18 UTC, merged