created mt_service_api
bunjovis/ConnectedCircularity pull request #9
Opened 2022-10-08 18:34 UTC by MSurvonen

2022-10-09 06:07 UTC, bunjovis requested changes
the files should be moved to cc-mt-service folder. Otherwise looking good. One common comment to everyone doing these API services: be careful when using generated code, you still have to know what the code is doing, how to use it or modify it.

2022-10-09 15:01 UTC, OpaJaa requested changes

2022-10-09 15:01 UTC, OpaJaa commented on cc-mt-service/openapi.yaml
> +                $ref: "#/v1/components/schemas/Added"
Remove /v1/

2022-10-09 15:01 UTC, OpaJaa commented on cc-mt-service/openapi.yaml
> +                $ref: "#/v1/components/schemas/Error"
Remove /v1/

2022-10-09 15:01 UTC, OpaJaa commented on cc-mt-service/openapi.yaml
> +              type: array
array needs items. https://swagger.io/docs/specification/data-models/data-types/#array

2022-10-09 15:01 UTC, OpaJaa commented on cc-mt-service/openapi.yaml
> +              type: array
Same here.

2022-10-09 16:37 UTC, hannakortetjarvi commented on cc-mt-service/openapi.yaml
> +openapi: '3.0.2'
backend and pk service design documents are using openapi 3.0.3, should all use the same version?

2022-10-11 05:59 UTC, OpaJaa submitted a review, later dismissed

2022-10-11 14:27 UTC, rvsape approved these changes, later dismissed

2022-10-12 06:43 UTC, hannakortetjarvi approved these changes

2022-10-13 15:29 UTC, bunjovis approved these changes

2022-10-13 19:40 UTC, OpaJaa approved these changes

2022-10-16 11:45 UTC, merged